[package]
name = "website"
version = "0.1.0"
authors = ["Brendan Arciszewski <git@brendanarciszewski.ca>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"