[build]
publish = "public"
command = "echo 'deploy with CI' && test '1' = '0'"

[build.processing]
skip_processing = false

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true
